service: rise-riscv-runner-app

provider:
  name: scaleway
  scwRegion: ${env:SCW_DEFAULT_REGION, "fr-par"}
  scwProject: ${env:SCW_DEFAULT_PROJECT_ID, "03a2e06e-e7c1-45a6-9f05-775d813c2e28"}
  scwToken: ${env:SCW_SECRET_KEY}

plugins:
  - serverless-scaleway-functions

package:
  patterns:
    - "!node_modules/**"
    - "!.gitignore"
    - "!.git/**"

custom:
  containers:
    gh-webhook:
      registryImage: ${env:REGISTRY}/${env:IMAGE}:latest
      port: 8080
      memoryLimit: 256
      cpuLimit: 100
      secret:
        GHAPP_WEBHOOK_SECRET: ${env:GHAPP_WEBHOOK_SECRET}
        GHAPP_PRIVATE_KEY: ${env:GHAPP_PRIVATE_KEY}
        K8S_KUBECONFIG: ${env:K8S_KUBECONFIG}
        REDIS_URL: ${env:REDIS_URL}
      env:
        PROD: "true"
        PROD_URL: ${env:PROD_URL}
        STAGING_URL: ${env:STAGING_URL}
      # Health check configuration
      healthCheck:
        type: http
        httpPath: /health
        interval: 10s
        failureThreshold: 3
      # VPC for Redis access
      privateNetworkId: "58fa41d0-f6a4-4b6f-8f65-b788563842c1"

    gh-webhook-staging:
      registryImage: ${env:REGISTRY}/${env:IMAGE}:staging
      port: 8080
      memoryLimit: 256
      cpuLimit: 100
      secret:
        GHAPP_WEBHOOK_SECRET: ${env:GHAPP_WEBHOOK_SECRET}
        GHAPP_PRIVATE_KEY: ${env:GHAPP_PRIVATE_KEY}
        K8S_KUBECONFIG: ${env:K8S_KUBECONFIG}
        REDIS_URL: ${env:REDIS_URL}
      env:
        PROD: "false"
        PROD_URL: ${env:PROD_URL}
        STAGING_URL: ${env:STAGING_URL}
      # Health check configuration
      healthCheck:
        type: http
        httpPath: /health
        interval: 10s
        failureThreshold: 3
      # VPC for Redis access
      privateNetworkId: "58fa41d0-f6a4-4b6f-8f65-b788563842c1"
